"use client";

export default function TermsPage() {
  return (
    <div className="min-h-screen px-6 py-12" style={{ background: "#0B1120" }}>
      <div className="max-w-2xl mx-auto">
        <div className="mb-10">
          <h1 className="text-2xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: April 2025</p>
        </div>

        <div className="space-y-8 text-gray-400 text-sm leading-relaxed">

          <section>
            <h2 className="text-white font-semibold text-base mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using Hinilas Pro (&quot;the Platform&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">2. Description of Service</h2>
            <p>Hinilas Pro is an AI-powered marketing tool that helps business owners generate market research, ad angles, sales copy, and ad creatives for use in Meta Ads campaigns. The Platform operates on a credit-based system with tiered access.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">3. Accounts</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must sign in using a valid Google or Facebook account.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You may not share your account with others or use another person&apos;s account.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">4. Credits and Payments</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Credits are purchased via GCash and are non-refundable once added to your account.</li>
              <li>Credits never expire and carry over indefinitely.</li>
              <li>Your tier (Lite, Flex, Max) is determined automatically based on your credits remaining.</li>
              <li>We reserve the right to adjust credit costs for features with prior notice.</li>
              <li>Fraudulent payment submissions will result in immediate account termination.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">5. Referral Program</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You may refer other users using your unique referral link.</li>
              <li>Referral rewards are credited once per referred account and are subject to verification.</li>
              <li>We reserve the right to revoke referral rewards if abuse or manipulation is detected.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">6. AI-Generated Content</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>All content generated by the Platform is provided as-is for marketing assistance purposes.</li>
              <li>You are solely responsible for reviewing, editing, and using any AI-generated content.</li>
              <li>Hinilas Pro does not guarantee that AI-generated content will produce specific advertising results.</li>
              <li>Do not use generated content to make false, misleading, or illegal claims.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">7. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Use the Platform for any unlawful, fraudulent, or harmful purpose</li>
              <li>Attempt to reverse-engineer, scrape, or copy the Platform&apos;s systems or AI outputs at scale</li>
              <li>Use the Platform to generate content that violates Meta&apos;s advertising policies</li>
              <li>Abuse the credit system, referral program, or any promotional offers</li>
              <li>Share or resell access to your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">8. Intellectual Property</h2>
            <p>The Hinilas Pro platform, logo, and underlying systems are owned by Webcake Mechanic / KRA. AI-generated outputs you create using the Platform belong to you, subject to the acceptable use terms above.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">9. Disclaimer of Warranties</h2>
            <p>The Platform is provided &quot;as is&quot; without warranties of any kind. We do not guarantee uninterrupted access, specific advertising results, or that AI outputs will be error-free. Use at your own discretion.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">10. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Hinilas Pro shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Platform, including ad spend losses or business outcomes.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">11. Changes to Terms</h2>
            <p>We may update these terms at any time. Continued use of the Platform after changes are posted constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">12. Governing Law</h2>
            <p>These terms are governed by the laws of the Republic of the Philippines. Any disputes shall be resolved under Philippine jurisdiction.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-base mb-2">13. Contact</h2>
            <p>For any questions regarding these terms, contact us at:</p>
            <p className="mt-1 text-white">support@hinilas.pro</p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-gray-800">
          <p className="text-gray-600 text-xs text-center">© 2025 Hinilas Pro — Basta Mag Ads Hilas</p>
        </div>
      </div>
    </div>
  );
}
